#!/bin/bash
AVG_MAX=3                        # maximum load avg
BOT_ID="your_telegram_bot_token" # t.me bot token
CHAT_ID="your_chat_id"           # t.me chat id
PASTE_KEY="your_paste_key"       # pastebin.com api developer key

TG_URL="https://api.telegram.org/bot$BOT_ID/sendMessage"

AVG=$(awk -v avg_max=${AVG_MAX} '$1>avg_max{print $1}' /proc/loadavg)
N=$'\n'
if [ -n "$AVG" ]; then
    UPTIME=$(uptime)
    if [ -n "$PASTE_KEY" ]; then
        PASTE="$UPTIME $N $N $(ps -eo pid,ppid,user,cmd,%mem,%cpu --sort=-%cpu | head) $N $N $(ps -eo pid,ppid,user,cmd,%mem,%cpu --sort=-%mem | head)"
        
        if [ -x "/usr/bin/mysqladmin" ]; then
            PASTE="$PASTE $N $N $(mysqladmin processlist | head)"
        fi

        if [ -x "/usr/sbin/iotop" ]; then
            PASTE="$PASTE $N $N $(iotop -n 1 -q -t | head)"
        fi
        
        PASTE_RES=$(curl -X POST --data "api_option=paste&api_user_key=&api_paste_private=1&api_paste_name=high load&api_paste_expire_date=1D&api_paste_format=text&api_dev_key=$PASTE_KEY&api_paste_code=$PASTE" https://pastebin.com/api/api_post.php 2>/dev/null | sed 's/pastebin\.com\//pastebin.com\/raw\//')
    fi
    if [ -n "$BOT_ID" -a -n "$CHAT_ID" ]; then
        [ -z "${IP:=$(curl -s -m1 checkip.amazonaws.com)}" ] && [ -z "${IP:=$(curl -s -m1 ident.me)}" ] && [ -z "${IP:=$(curl -s -m1 ipinfo.io/ip)}" ]
        curl -X POST --data "chat_id=$CHAT_ID&parse_mode=html&text=$IP $N HIGH $UPTIME $N $PASTE_RES" $TG_URL >/dev/null 2>&1
        sleep 61s
        AVG=$(awk -v avg_max=${AVG_MAX} '$1<=avg_max{print $1}' /proc/loadavg)
        if [ -n "$AVG" ]; then
            UPTIME=$(uptime)
            curl -X POST --data "chat_id=$CHAT_ID&parse_mode=html&text=$IP $N NORM $UPTIME" $TG_URL >/dev/null 2>&1
        fi
    fi
fi

# successful installation marker

exit 0
